#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \

### ARCHIVE EXTRACTION
# usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   unzstd $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../..'
alias .5='cd ../../../..'
alias .6='cd ../../../../..'
alias cdp='cd ~/Projects'
alias cdc='cd ~/Courses'
alias cdP='cd ~/Pictures'
alias cdd='cd ~/Downloads'
alias cdD='cd ~/Documents'

# My aliases
alias \
  bright="xrandr --output eDP-1 --brightness" \
  td="sudo timedatectl set-ntp true" \
  kbe="setxkbmap es" \
  kbu="setxkbmap us" \
  ytm="youtube-dl --add-metadata --extract-audio --audio-format mp3" \
  ytv="youtube-dl -f bestvideo+bestaudio" \
  tor="bash $HOME/Downloads/tor-browser_en-US/Browser/start-tor-browser" \
  sd="signal-desktop" \
  r="ranger" \
  t="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
  tor="bash .tor-browser_en-US/Browser/start-tor-browser" \

# For development
alias \
  urcontroller="sudo bash /home/max/ursim-3.14.3.1031232/controller.sh" \
  urinterface="sudo bash /home/max/ursim-3.14.3.1031232/interface.sh" \
  py="python" \
  mongop="mongod --port 27017 --dbpath /home/max/database" \
  drun="dotnet run" \
  dbuild="dotnet build" \
  dres="dotnet restore" \
  dnuget="dotnet add package" \
  ngs="ng serve" \
  ngt="ng test" \
  config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'
